name: testScript
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build my virtual OS

    runs-on: Ubuntu-latest

    steps:
    - name: checkout my codes
      uses: actions/checkout@v4
      with:
        path: main
        
    - name: Checkout private repo remotely
      uses: actions/checkout@v4
      with:
        repository: sandytangps/calculator
        #path: <folder of choice>
        #token: ${{ secrets.MY_TOKEN }}
        path: testScript

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install python
      run: |
        python -m pip install --upgrade pip
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest  testScript.calculator.py --junitxml=junit/test-results.xml
#    - name: if py test is success
#      if: ${{success()}}
        