name: testScript
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build my virtual OS

    runs-on: Ubuntu-latest

    steps:
    - name: checkout my codes
      uses: actions/checkout@v4
    
    - name: extract the script
      run: |
        git fetch ./calculator.py
        
    - name: Checkout private repo remotely
      uses: actions/checkout@v4
      with:
        repository: sandytangps/calculator
        #path: <folder of choice>
        #token: ${{ secrets.MY_TOKEN }}
    - name: get repo
      run: |
        ls -alch
        git fetch ./test_calculator.py
      #run: |
      #  $testFile = ${find . -type f -name 'test_*'}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest $testFile --junitxml=junit/test-results.xml
#    - name: if py test is success
#      if: ${{success()}}
        